apiVersion: v1
kind: DeploymentConfig
metadata:
  name: calories-tracker
  namespace: oddsprep
  selfLink: /oapi/v1/namespaces/oddsprep/deploymentconfigs/calories-tracker
  uid: 9147c1a3-732f-11e7-ab22-12b5519f9b58
  resourceVersion: '48162982'
  generation: 45
  creationTimestamp: '2017-07-28T00:56:19Z'
  labels:
    app: calories-tracker
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - calories-tracker
        from:
          kind: ImageStreamTag
          namespace: oddsprep
          name: 'calories-tracker:latest'
        lastTriggeredImage: >-
          salientcrgt/calories-tracker@sha256:6fb3d7bc27022d71f822a720b830310d792083e204d1fb313ba99344639c6fa4
  replicas: 1
  test: false
  selector:
    app: calories-tracker
    deploymentconfig: calories-tracker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: calories-tracker
        deploymentconfig: calories-tracker
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: calories-tracker
          image: >-
            salientcrgt/calories-tracker@sha256:6fb3d7bc27022d71f822a720b830310d792083e204d1fb313ba99344639c6fa4
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ODDS_USER
              value: odds
            - name: ODDS_PASS
              value: m1r@cL3
            - name: ODDS_DB_URL
              value: 'postgresql://postgresql.oddsprep.svc:5432/calories_tracker'
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 35
  observedGeneration: 45
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: oddsprep
            name: 'calories-tracker:latest'
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-08-04T17:36:42Z'
      lastTransitionTime: '2017-08-04T17:36:41Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "calories-tracker-35" successfully rolled out
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-08-05T04:38:34Z'
      lastTransitionTime: '2017-08-05T04:38:34Z'
      message: Deployment config has minimum availability.
  readyReplicas: 1
