apiVersion: v1
kind: Service
metadata:
  name: calories-tracker
  namespace: oddsprep
  selfLink: /api/v1/namespaces/oddsprep/services/calories-tracker
  uid: 91508c7a-732f-11e7-ab22-12b5519f9b58
  resourceVersion: '41517032'
  creationTimestamp: '2017-07-28T00:56:19Z'
  labels:
    app: calories-tracker
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: calories-tracker
    deploymentconfig: calories-tracker
  clusterIP: 172.30.192.176
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
