apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: odds-test
  selfLink: /api/v1/namespaces/odds-test/services/postgresql
  labels:
    app: postgresql-persistent
    template: postgresql-persistent-template
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgresql
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
