apiVersion: v1
kind: Route
metadata:
  name: calories-tracker
  namespace: odds-test
  selfLink: /oapi/v1/namespaces/odds-test/routes/calories-tracker
  uid: ad83bb4a-732f-11e7-ab22-12b5519f9b58
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: calories-tracker-oddsprep.b9ad.pro-us-east-1.openshiftapps.com
  to:
    kind: Service
    name: calories-tracker
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
status:
  ingress:
    - host: calories-tracker-oddsprep.b9ad.pro-us-east-1.openshiftapps.com
      routerName: router
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
