apiVersion: v1
kind: Route
metadata:
  name: postgresql
  namespace: odds-test
  selfLink: /oapi/v1/namespaces/odds-test/routes/postgresql
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: postgresql-oddsprep.b9ad.pro-us-east-1.openshiftapps.com
  to:
    kind: Service
    name: postgresql
    weight: 100
  port:
    targetPort: postgresql
  wildcardPolicy: None
status:
  ingress:
    - host: postgresql-oddsprep.b9ad.pro-us-east-1.openshiftapps.com
      routerName: router
      conditions:
        - type: Admitted
          status: 'True'
     wildcardPolicy: None
